library(gplots)
library(RColorBrewer)
library(limma)
library(edgeR)
library(heatmap3)
data = read.table("/home/vk/sdld.csv", header=TRUE, com='',sep="\t")
rnames <- data.matrix(data[,1])
mat_data <- data.matrix(data[2:ncol(data)]) 
#colnames(mat_data)<-c("Pathway","Short-Day","Long-Day")
rownames(mat_data)<-rnames
#my_palette <- colorRampPalette(c("red","brown","yellow", "green","cyan","purple","blue","violet","black"))(n = 999)
#my_palette <- colorRampPalette(c("red","orange","blue","black"))(n = 999)
#my_palette <- colorRampPalette(c("white","yellow","orange","red","black"))(n = 20)
#my_palette <- colorRampPalette(c("black","green","yellow","orange","red","cyan","blue"))(n = 99)
my_palette <- colorRampPalette(c("blue","cyan","green","yellow","orange","red","brown","black"))(n = 999)
png("/home/vk/sdld.heatmap.png", width = 5*350, height = 5*450, res = 350, pointsize =9)
#heatmap.2((mat_data),margins =c(7.5,6),col=my_palette, dendrogram="row",scale="column",xlab = "Photoperiodic Conditions",ylab = "Genes")
heatmap.2((mat_data),margins =c(8,16),col=my_palette,dendrogram = "none", scale= NULL, distfun = dist,xlab = "-----------Photoperiodic conditions-----------",ylab = "-----------Pathways-----------")
dev.off()