library (foreign)
#dat <- read.delim("/home/vk/hypo/assembly/castrated_spring_autumn/sam/tg1/dge_gene_sc_si_input.tsv.Control_vs_Treated.edgeR.DE_results.xls", header =TRUE)
#dat <- read.delim("/media/vk/Seagate Backup Plus Drive/SETH -8 samples.LIU.16 Nov17. F16FTSSWKF1013_SPOcqhE/8/result/Spodoptera_litura/Transcriptome_resequencing_report/BGI_result/3.QuantitativeAnalysis/GeneAndIsoformExp/new/dge/volcano plot/dge_P_Set2Set4_volcano.csv", header =TRUE)
dat <- read.csv("/home/vk/liver/gf/dge/significantdge/DAVID/m17r17/volcano plot/volcano_m17_r17_volcanoplot_all.csv", header =TRUE, sep = '\t')
head(dat)
with(dat, plot(logFC, -log10(PValue), pch= 23, main = "Migratory_ZT17 vs. Refractory_ZT17", xlim= c(-20,20), ylim = c(0.25,14)))
#with(subset(dat,PValue < 0.05), points(logFC, -log10(PValue), pch=20, col= "BLACK"))
with(subset(dat, PValue < 0.0055 & logFC< -5), points(logFC, -log10(PValue), pch=20, col= "red"))
with(subset(dat, PValue < 0.0055 & logFC>5), points(logFC, -log10(PValue), pch=20, col= "red"))
with(subset(dat, PValue < 0.0055 & logFC> -5 & logFC< -4), points(logFC, -log10(PValue), pch=20, col= "orange"))
with(subset(dat, PValue < 0.0055 & logFC< 5 & logFC> 4), points(logFC, -log10(PValue), pch=20, col= "orange"))
with(subset(dat, PValue < 0.0055 & logFC> -4 & logFC< -3), points(logFC, -log10(PValue), pch=20, col= "yellow"))
with(subset(dat, PValue < 0.0055 & logFC< 4 & logFC> 3), points(logFC, -log10(PValue), pch=20, col= "yellow"))
with(subset(dat, PValue < 0.0055 & logFC> -3 & logFC< -2), points(logFC, -log10(PValue), pch=20, col= "green"))
with(subset(dat, PValue < 0.0055 & logFC< 3 & logFC> 2), points(logFC, -log10(PValue), pch=20, col= "green"))
with(subset(dat, PValue < 0.0055 & logFC> -2 & logFC< 0), points(logFC, -log10(PValue), pch=20, col= "black"))
with(subset(dat, PValue < 0.0055 & logFC< 2 & logFC> 0), points(logFC, -log10(PValue), pch=20, col= "black"))
library(MASS)
library(calibrate)
with(subset(dat, (-log10(PValue)>5) & (-log10(PValue)<100) & (logFC>5 & logFC< 100) | (-log10(PValue)>4) & (-log10(PValue)<100)& (logFC>-100 & logFC< -5)), textxy(logFC, -log10(PValue), labs= Gene, cex=1))